USE [master]
GO

CREATE DATABASE [CurrentAccountAPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CurrentAccountAPI', FILENAME = N'C:\Users\CurrentAccountAPI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CurrentAccountAPI_log', FILENAME = N'C:\Users\CurrentAccountAPI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CurrentAccountAPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CurrentAccountAPI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET ARITHABORT OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CurrentAccountAPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CurrentAccountAPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CurrentAccountAPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CurrentAccountAPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CurrentAccountAPI] SET  MULTI_USER 
GO

ALTER DATABASE [CurrentAccountAPI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CurrentAccountAPI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CurrentAccountAPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CurrentAccountAPI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CurrentAccountAPI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CurrentAccountAPI] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CurrentAccountAPI] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CurrentAccountAPI] SET  READ_WRITE 
GO